version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: CarralS
      MYSQL_PASSWORD: sergio123
      MYSQL_ROOT_PASSWORD: sergop1234

    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    conteiner_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: sergio123
    ports:
      - "8080:80"
